# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1250, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1250, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1250, 800))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 219, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 92, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 219, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 219, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 92, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 219, 201))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 92, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(21, 255, 210))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(10, 219, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 92, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 123, 99))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 92, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 92, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 184, 148))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(459, 139, 770, 620))
        self.graphicsView.setMinimumSize(QtCore.QSize(700, 550))
        self.graphicsView.setMaximumSize(QtCore.QSize(10000, 10000))
        self.graphicsView.setObjectName("graphicsView")
        self.exploreStep = QtWidgets.QPushButton(self.centralwidget)
        self.exploreStep.setGeometry(QtCore.QRect(20, 720, 401, 41))
        self.exploreStep.setObjectName("exploreStep")
        self.exploreTime = QtWidgets.QPushButton(self.centralwidget)
        self.exploreTime.setGeometry(QtCore.QRect(20, 660, 401, 41))
        self.exploreTime.setObjectName("exploreTime")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 140, 411, 251))
        self.groupBox.setObjectName("groupBox")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.label_5.setObjectName("label_5")
        self.x_start = QtWidgets.QLineEdit(self.groupBox)
        self.x_start.setGeometry(QtCore.QRect(50, 60, 141, 31))
        self.x_start.setObjectName("x_start")
        self.y_start = QtWidgets.QLineEdit(self.groupBox)
        self.y_start.setGeometry(QtCore.QRect(50, 100, 141, 31))
        self.y_start.setObjectName("y_start")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(210, 60, 31, 31))
        self.label_6.setObjectName("label_6")
        self.y_end = QtWidgets.QLineEdit(self.groupBox)
        self.y_end.setGeometry(QtCore.QRect(250, 100, 141, 31))
        self.y_end.setObjectName("y_end")
        self.x_end = QtWidgets.QLineEdit(self.groupBox)
        self.x_end.setGeometry(QtCore.QRect(250, 60, 141, 31))
        self.x_end.setObjectName("x_end")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(210, 100, 31, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 30, 181, 31))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(200, 30, 191, 31))
        self.label_9.setObjectName("label_9")
        self.drawCoreLine = QtWidgets.QPushButton(self.groupBox)
        self.drawCoreLine.setGeometry(QtCore.QRect(10, 200, 181, 41))
        self.drawCoreLine.setObjectName("drawCoreLine")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 160, 381, 41))
        self.label_10.setObjectName("label_10")
        self.drawCmpLine = QtWidgets.QPushButton(self.groupBox)
        self.drawCmpLine.setGeometry(QtCore.QRect(220, 200, 181, 41))
        self.drawCmpLine.setObjectName("drawCmpLine")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 410, 411, 241))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.label_11.setObjectName("label_11")
        self.y_center = QtWidgets.QLineEdit(self.groupBox_2)
        self.y_center.setGeometry(QtCore.QRect(50, 100, 141, 31))
        self.y_center.setObjectName("y_center")
        self.x_center = QtWidgets.QLineEdit(self.groupBox_2)
        self.x_center.setGeometry(QtCore.QRect(50, 60, 141, 31))
        self.x_center.setObjectName("x_center")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 105, 31, 21))
        self.label_12.setObjectName("label_12")
        self.step_angle = QtWidgets.QLineEdit(self.groupBox_2)
        self.step_angle.setGeometry(QtCore.QRect(240, 60, 141, 31))
        self.step_angle.setObjectName("step_angle")
        self.label_15 = QtWidgets.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(210, 60, 31, 31))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(380, 50, 20, 31))
        self.label_16.setObjectName("label_16")
        self.drawCoreRound = QtWidgets.QPushButton(self.groupBox_2)
        self.drawCoreRound.setGeometry(QtCore.QRect(10, 190, 181, 41))
        self.drawCoreRound.setObjectName("drawCoreRound")
        self.drawCmpRound = QtWidgets.QPushButton(self.groupBox_2)
        self.drawCmpRound.setGeometry(QtCore.QRect(220, 190, 181, 41))
        self.drawCmpRound.setObjectName("drawCmpRound")
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(20, 160, 361, 31))
        self.label_17.setObjectName("label_17")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(10, 30, 181, 31))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(210, 30, 181, 31))
        self.label_14.setObjectName("label_14")
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(200, 105, 41, 21))
        self.label_18.setObjectName("label_18")
        self.length = QtWidgets.QLineEdit(self.groupBox_2)
        self.length.setGeometry(QtCore.QRect(240, 100, 141, 31))
        self.length.setObjectName("length")
        self.coreBox = QtWidgets.QComboBox(self.centralwidget)
        self.coreBox.setGeometry(QtCore.QRect(330, 10, 381, 41))
        self.coreBox.setObjectName("coreBox")
        self.coreBox.addItem("")
        self.coreBox.addItem("")
        self.coreBox.addItem("")
        self.coreBox.addItem("")
        self.coreBox.addItem("")
        self.coreBox.addItem("")
        self.compareBox = QtWidgets.QComboBox(self.centralwidget)
        self.compareBox.setGeometry(QtCore.QRect(330, 60, 381, 41))
        self.compareBox.setObjectName("compareBox")
        self.compareBox.addItem("")
        self.compareBox.addItem("")
        self.compareBox.addItem("")
        self.compareBox.addItem("")
        self.compareBox.addItem("")
        self.compareBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 301, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 301, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(750, 10, 341, 41))
        self.label_3.setObjectName("label_3")
        self.redSwitch = QtWidgets.QRadioButton(self.centralwidget)
        self.redSwitch.setGeometry(QtCore.QRect(750, 70, 81, 31))
        self.redSwitch.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("R.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.redSwitch.setIcon(icon)
        self.redSwitch.setIconSize(QtCore.QSize(40, 40))
        self.redSwitch.setObjectName("redSwitch")
        self.greenSwitch = QtWidgets.QRadioButton(self.centralwidget)
        self.greenSwitch.setGeometry(QtCore.QRect(840, 70, 81, 31))
        self.greenSwitch.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("G.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.greenSwitch.setIcon(icon1)
        self.greenSwitch.setIconSize(QtCore.QSize(40, 40))
        self.greenSwitch.setObjectName("greenSwitch")
        self.blueSwitch = QtWidgets.QRadioButton(self.centralwidget)
        self.blueSwitch.setGeometry(QtCore.QRect(930, 70, 81, 31))
        self.blueSwitch.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("B.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blueSwitch.setIcon(icon2)
        self.blueSwitch.setIconSize(QtCore.QSize(40, 40))
        self.blueSwitch.setChecked(False)
        self.blueSwitch.setObjectName("blueSwitch")
        self.blackSwitch = QtWidgets.QRadioButton(self.centralwidget)
        self.blackSwitch.setGeometry(QtCore.QRect(1020, 70, 81, 31))
        self.blackSwitch.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Black.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.blackSwitch.setIcon(icon3)
        self.blackSwitch.setIconSize(QtCore.QSize(40, 40))
        self.blackSwitch.setChecked(True)
        self.blackSwitch.setObjectName("blackSwitch")
        self.clearCanvas = QtWidgets.QPushButton(self.centralwidget)
        self.clearCanvas.setGeometry(QtCore.QRect(1110, 0, 141, 121))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.clearCanvas.setFont(font)
        self.clearCanvas.setAcceptDrops(False)
        self.clearCanvas.setObjectName("clearCanvas")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 380, 421, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(720, 0, 20, 121))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 110, 1241, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(430, 120, 21, 680))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1250, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Реализация и исследование алгоритмов построения отрезков"))
        self.exploreStep.setText(_translate("MainWindow", "Исследование ступенчатости"))
        self.exploreTime.setText(_translate("MainWindow", "Исследование времени"))
        self.groupBox.setTitle(_translate("MainWindow", "Построение одиночных отрезков"))
        self.label_4.setText(_translate("MainWindow", "Xн"))
        self.label_5.setText(_translate("MainWindow", "Yн"))
        self.x_start.setText(_translate("MainWindow", "70"))
        self.y_start.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Xк"))
        self.y_end.setText(_translate("MainWindow", "50"))
        self.x_end.setText(_translate("MainWindow", "23"))
        self.label_7.setText(_translate("MainWindow", "Yк"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Начало</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Конец</p></body></html>"))
        self.drawCoreLine.setText(_translate("MainWindow", "Основной"))
        self.label_10.setText(_translate("MainWindow", "Отрезок с помощью алгоритма:"))
        self.drawCmpLine.setText(_translate("MainWindow", "Сравнительный"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Сравнение визуальных характеристик"))
        self.label_11.setText(_translate("MainWindow", "Xц"))
        self.y_center.setText(_translate("MainWindow", "350"))
        self.x_center.setText(_translate("MainWindow", "350"))
        self.label_12.setText(_translate("MainWindow", "Yц"))
        self.step_angle.setText(_translate("MainWindow", "3"))
        self.label_15.setText(_translate("MainWindow", "∠"))
        self.label_16.setText(_translate("MainWindow", " °"))
        self.drawCoreRound.setText(_translate("MainWindow", "Основной"))
        self.drawCmpRound.setText(_translate("MainWindow", "Сравнительный"))
        self.label_17.setText(_translate("MainWindow", "Лучи с помощью алгоритма:"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Центр</p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Шаг, Длина</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "Len"))
        self.length.setText(_translate("MainWindow", "200"))
        self.coreBox.setItemText(0, _translate("MainWindow", "Цифрового диф. анализатора"))
        self.coreBox.setItemText(1, _translate("MainWindow", "Брезенхема (нецелые числа)"))
        self.coreBox.setItemText(2, _translate("MainWindow", "Брезенхема (целые числа)"))
        self.coreBox.setItemText(3, _translate("MainWindow", "Брезенхема (со сглаживанием)"))
        self.coreBox.setItemText(4, _translate("MainWindow", "By"))
        self.coreBox.setItemText(5, _translate("MainWindow", "Метод Qt"))
        self.compareBox.setItemText(0, _translate("MainWindow", "Цифрового диф. анализатора"))
        self.compareBox.setItemText(1, _translate("MainWindow", "Брезенхема (нецелые числа)"))
        self.compareBox.setItemText(2, _translate("MainWindow", "Брезенхема (целые числа)"))
        self.compareBox.setItemText(3, _translate("MainWindow", "Брезенхема (со сглаживанием)"))
        self.compareBox.setItemText(4, _translate("MainWindow", "By"))
        self.compareBox.setItemText(5, _translate("MainWindow", "Метод Qt"))
        self.label.setText(_translate("MainWindow", "Основной алгоритм"))
        self.label_2.setText(_translate("MainWindow", "Сравнительный алгоритм"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Цвет основного алгоритма</p></body></html>"))
        self.clearCanvas.setText(_translate("MainWindow", "Очистить\n"
" экран"))
